printf "\e[37;45m"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python3.4.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-RPi.GPIO.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-cracklib.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-libproxy.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python-ntplib.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python3.4-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/python3.4.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/glib2-python.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/hostapd.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/libnl.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/libssh2-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/libssh2.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/lighttpd-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/lighttpd.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/samba4-lib.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/samba4.tcz"


