printf "\e[47;45m"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc-doc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc-locale.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc_base-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc_libs-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gcc_libs.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/cloog-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/cloog.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/isl-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/isl.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/mpc-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/mpc-doc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/mpc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/mpfr.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gmp-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gmp-doc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/gmp.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/binutils-dev.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/binutils-doc.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/binutils-locale.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/binutils.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/glib2.tcz"
wget "http://repo.tinycorelinux.net/7.x/armv6/tcz/glibc_base-dev.tcz"



